services:
  api:
    build: 
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env
    container_name: pigmeu-api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=pigmeu
      - REDIS_URL=redis://redis:6379
      - APP_ENV=development
      - LOG_LEVEL=INFO
    depends_on:
      - redis
      - mongo
    volumes:
      - ../:/app
      - /app/__pycache__
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - pigmeu-network

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    env_file:
      - ../.env
    container_name: pigmeu-worker
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=pigmeu
      - REDIS_URL=redis://redis:6379
      - APP_ENV=development
      - LOG_LEVEL=INFO
    depends_on:
      - redis
      - mongo
    volumes:
      - ../:/app
      - /app/__pycache__
    command: celery -A src.workers.worker worker --loglevel=info --concurrency=2
    networks:
      - pigmeu-network

  redis:
    image: redis:7-alpine
    container_name: pigmeu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pigmeu-network

  mongo:
    image: mongo:7
    container_name: pigmeu-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pigmeu-network

volumes:
  redis_data:
  mongo_data:

networks:
  pigmeu-network:
    driver: bridge
